### ISSUE TITLE
Annual report failing. Likely due to API size restrictions.

### ISSUE THREAD

**Issue by UnconditionedLife** [UnconditionedLife/smum#125]

**Comment by kjain14** [comment]
Running annual report for 2021 on prod database leads to too many requests in a short period of time.

Solution would be to make a API for querying services by month, but might run into record limits.

Think about if we can get field values from services

**Comment by kjain14** [comment]
Running New Clients report for December 2021 results in too many requests to the server, causing the max threshold to be exceeded.

In order to fix this we would need a to keep whether it was the clients first month being served (true or false) as a part of the service object, along with the zip code of the client served.

Think about what fields we need in service.

**Comment by kjain14** [comment]
New Client Report: Specifically, we would want service records to have a new flag for isFirstService. We may also need serviceMonth.

Annual Report: Pagination may be the best solution here.
