### ISSUE TITLE
Feature: Notify user of any Active "other" or "child" dependents 18 or older.

### ISSUE THREAD

**Issue by UnconditionedLife** [UnconditionedLife/smum#37]
- When a client is loaded there should be a check to see if any dependents are 18 or older, a relationship of "Child" and a status of "Active".
- If one exists the dependent should be set to "Inactive"
- A pop message should notify the user of the change (name, age, new status)

**Comment by UnconditionedLife** [comment]
@scott-r  Once a child ages out. We need to deactivate them from the parent's account. Unfortunately, the volunteers don't have the time to check the dependents tab on the regular basis. The above is an idea of how to help with the problem.
What do you think of the solution and do you think you might be able to work on this issue?

**Comment by scott-r** [comment]
@UnconditionedLife It seems like checking (and updating the record) each time it is loaded would work. I assume that nothing special would happen the next time the client is loaded because the dependent is already inactive. I suppose it could also be done as a background task once a day.

Questions:
- Are there dependent relationships other than "child" where this rule would not apply?
- Is the notification just that, or is there an option not to make the change? If it's just a notification, is it really useful for the user to know that *this* is the moment when the change was made?

**Comment by UnconditionedLife** [comment]
That's right, once a dependent record is marked 'Inactive' it should remain that way. Doing it in the background is not preferable because of the opportunity to engage with the client. The goal is to validate the age of the child with the parent. Also, to remind the parent that the child no longer qualifies, but that they can apply on her/his own if they are also low income.

Answers:
- Good question. There is also the 'Other' relationship, it's generally for individuals who are not of child age but are dependents of the client. In limited cases, it may also apply to dependent children who are not their child but think we should not deal with the 'Other' relationships at this time.
- We should make the change and notify the user. If for some reason the change needs to be undone, the user can do that. It should happen very infrequently.
- It might be nice to print out a receipt that invites the now adult to apply for their own account?

**Comment by UnconditionedLife** [comment]
@scott-r Please assign this to yourself if you can take it on.

**Comment by scott-r** [comment]
Unless this is really urgent, I plan to finish working on the printer functionality first.

**Comment by UnconditionedLife** [comment]
I have added a check and global message if a dependent is over 17 and "Child" or "Other."
