### ISSUE TITLE
Bug: Target - Child not Working

### ISSUE THREAD

**Issue by kjain14** [UnconditionedLife/smum#39]
![image](https://user-images.githubusercontent.com/8972749/42302163-153d8aea-8037-11e8-9343-b4a7ded6b502.png)
![image](https://user-images.githubusercontent.com/8972749/42302172-26b11dd2-8037-11e8-9e5d-de63806143b1.png)
Target of first step is child, yet a dependent who is not a child is still counted in the services

**Comment by UnconditionedLife** [comment]
The relationship is not being used to identify a child. Since a 'Spouse' or 'Other Dependent' can be under 18 years of age and/or have a grade. The function is checking for a dependent that has a grade matching the targets set out in the ServiceType.

@kjain14 please confirm that this is actually behaving as set out above.

**Comment by kjain14** [comment]
Relationship is working as above.
