### ISSUE TITLE
Redesign the client.lastServed object.

### ISSUE THREAD

**Issue by UnconditionedLife** [UnconditionedLife/smum#75]
1) Store the latest instance of each serviceType, not just each serviceCategory.
2) Move idCheckedDate fully into LastServed.
3) Create a mechanism for maintaining a relationship between voucher and voucherFulfill serviceTypes.

**Comment by scott-r** [comment]
It looks to me like a given service has the following properties that constrain when and for which clients it is available. Not all of these properties will be set for every service.
- Start and end dates when the service is active.
- Non-time-based criteria for which clients are eligible (e.g. homeless, has children, etc.).
- Minimum interval since last use of this service.
- Maximum number of uses within the active interval (usually 1, but could be another number).

Given that, it seems that we should be tracking the last service date for each **category** of service, e.g. a single last service date for food. Minimum intervals for USDA and non-USDA food would apply to the last use of any service in the food category. 

Let's use the term **targeted** for services that are active at the current time and for which the client meets the eligibility criteria other than time, and **available** for targeted services where the client also meets the time criteria. Then I would propose that we should show UI buttons for all **targeted** services but disable the buttons for those that are not **available**. Within the food category, we would show the button for the first available service in the order (USDA, Non-USDA, Emergency).

It would be nice to show the last served and possibly next available dates for all the targeted services, possibly using hovertext for the button. *Implementation note*: We can call the same code to determine the service buttons every time a service is delivered. Then there is no need for special code to deactivate the service button that was just pressed.

**Comment by UnconditionedLife** [comment]
`LastServed` object has been deprecated in version 2.0.10
