### ISSUE TITLE
Feature: Add senior count to print receipts

### ISSUE THREAD

**Issue by UnconditionedLife** [UnconditionedLife/smum#86]
Now that seniors are not part of the adult count, family total no longer adds up.

**Comment by scott-r** [comment]
We need to reverse the previous change to receipts so that it shows only two categories: children and adults. This is because USDA forms, which are completed using the receipts, include only these two categories. Reports will continue to break down recipients in three age groups: children, adults, and seniors.

**Comment by scott-r** [comment]
@UnconditionedLife Should I be removing seniors from both food and clothing receipts or only food?

**Comment by UnconditionedLife** [comment]
I think that makes sense. It's not as critical, because clothing does not have the manual reporting process, but it's best to be consistent.

**Comment by scott-r** [comment]
Both the food and clothing receipts report total children and adults, where adults includes both seniors and working-age adults.
